apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mudadminimage 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mudadminimage 
    spec:
      containers:
        - name: mudadminimage 
          image: randomcontainerregistry.azurecr.io/mudadminimage
          ports:
          - containerPort: 4300